### PR TITLE
Add mechanism to allow extracting license text from files

### PR DESCRIPTION
**Pull request by rtabassum**
This change allows assembling license texts from targets in another repository. 

With the current implementation, there's no way to load license text file contents from an external repository. This change updates the `licenses_info_to_json()` method, which can be invoked by a rule that can assemble license texts in addition to all other license information. The JSON returned by the method only had the file paths as strings. This change constructs the list of File objects and returns that; so that it can be used to load file contents from an external repository using runfiles system.

- [ ] Tests pass
- [ ] Tests and examples for any new features.
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by rtabassum** [comment]
This can solve the issue mentioned in #68 for loading the license text from an external repository.

**Comment by aiuto** [comment]
This changes the output file format, right?
Can you give a condensed before/after in the CL description. Or, better, have an issue to discuss the problem. I'm having trouble seeing what you are solving. It seems like it is like the request to have LICENSE able to be able to point to a label rather than a strict file.

**Comment by aiuto** [comment]
As we discussed at the eng meeting, this seems good. 
Can you rebase to resolve the merge conflict.

**Comment by rtabassum** [comment]
@aiuto resolved the merge conflicts, its ready to be merged

**Comment by aiuto** [comment]
Can you rebase against head?  I don't understand why the tests are failing, but it looks like you might be fairly far behind head.

**Review by aiuto — APPROVED** [review]

**Pull request merged**
