### PR TITLE
Add `current_module_package_info` macro

### PR DESCRIPTION
**Pull request by fmeum**
This macro makes it easy for Bazel modules to declare a `package_info` without having to provide any information manually.

Work towards https://github.com/bazelbuild/bazel/discussions/23166

> It's a good idea to open an issue first for discussion.

- [x] Tests pass
- [x] Tests and examples for any new features.
- [x] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by fmeum** [comment]
@aiuto This is ready for review now that the Rules Authors SIG approved the purl spec: https://github.com/package-url/purl-spec/pull/317

**Comment by fmeum** [comment]
@aiuto Friendly ping

**Comment by fmeum** [comment]
@aiuto @shs96c Friendly ping

**Review by aiuto — APPROVED** [review]
Sorry for the slow response. I forgot to come back to this after I did the 1.0 release.

**Pull request merged**
