### PR TITLE
linty fresh

### PR DESCRIPTION
**Pull request by aiuto**
Correct some buildifer and Java error prone warnings.

### CODE REVIEW

**Review by danielmachlab — APPROVED** [review]
LGTM, Tony!

**Comment by aiuto** [comment]
Hi Daniel..   You actually need to do an approve in a review. 
I'm trying to be strict with myself about not doing forced merges.

**Comment by danielmachlab** [comment]
Hi Tony, I did give the PR an approval by giving it a review as it shows above my first comment. However, I do see you are still unable to merge. There is a message that says "at least 1 approving review is required by reviewers with write access". I am away from my computer today and can't tell if I still have write access. Could you double check that I do have write access?

**Comment by aiuto** [comment]
Ah ha!  It looks like you had read, but not write permissions in the repo. I changed to write and suddenly everything is approved. 
Thanks for your patience as I fight github's ACL system vs. my mental model.

**Comment by danielmachlab** [comment]
No worries, Tony!

**Pull request merged**
